---
apiVersion: v1
kind: ConfigMap
metadata:
    name: firewall-config-file
data:
    config.yaml: |
        allow tcp5201:
            proto: 6
            srcportoricmptypelast: 65535
            dstportoricmpcodefirst: 5201
            dstportoricmpcodelast: 5201
            ispermit: 1
        allow udp5201:
            proto: 17
            srcportoricmptypelast: 65535
            dstportoricmpcodefirst: 5201
            dstportoricmpcodelast: 5201
            ispermit: 1
        allow icmp:
            ispermit: 1
            proto: 1
            srcportoricmptypelast: 65535
            dstportoricmpcodelast: 65535
        forbid tcp8080:
            proto: 6
            srcportoricmptypelast: 65535
            dstportoricmpcodefirst: 8080
            dstportoricmpcodelast: 8080  
        forbid tcp80:
            proto: 6
            srcportoricmptypelast: 65535
            dstportoricmpcodefirst: 80
            dstportoricmpcodelast: 80
